/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { BookOpen, History, Scroll, User, Loader2, RefreshCw, Search, Share2 } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { generateHistoryStory } from './services/gemini';
import { DropdownMenu, DropdownMenuItem } from './components/DropdownMenu';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export default function App() {
  const [step, setStep] = useState<'entry' | 'story'>('entry');
  const [story, setStory] = useState<string>('');
  const [storyImage, setStoryImage] = useState<string | undefined>(undefined);
  const [loading, setLoading] = useState(false);
  const [userPrompt, setUserPrompt] = useState<string>('');
  const [narrativeStyle, setNarrativeStyle] = useState<string>('educational');
  const [storyLength, setStoryLength] = useState<string>('medium');
  const [hasApiKey, setHasApiKey] = useState<boolean>(false);
  const [selectedLanguage, setSelectedLanguage] = useState<string>('hi'); // Default to Hindi
  const [shareMessage, setShareMessage] = useState<string | null>(null);

  const languages = [
    { value: 'hi', label: 'Hindi' },
    { value: 'en', label: 'English' },
  ];

  const storyLengths = [
    { value: 'short', label: 'Choti' },
    { value: 'medium', label: 'Madhyam' },
    { value: 'long', label: 'Lambhi' },
  ];

  const narrativeStyles = [
    { value: 'educational', label: 'Shikshak' },
    { value: 'adventurous', label: 'Romanchak' },
    { value: 'mysterious', label: 'Rahasya-may' },
    { value: 'poetic', label: 'Kavyatmak' },
  ];

  const checkApiKey = async () => {
    if (window.aistudio) {
      const keySelected = await window.aistudio.hasSelectedApiKey();
      setHasApiKey(keySelected);
      return keySelected;
    }
    return false;
  };

  useEffect(() => {
    checkApiKey();
  }, []);

  const handleApiKeySelection = async () => {
    if (window.aistudio) {
      await window.aistudio.openSelectKey();
      setHasApiKey(true); // Assume success after opening dialog
    }
  };

  const startStory = async (prompt?: string, style: string = 'educational', length: string = 'medium', language: string = 'hi') => {
    if (!hasApiKey) {
      alert('Please select an API key to generate stories with images.');
      await handleApiKeySelection();
      return;
    }

    setStep('story');
    setLoading(true);
    setStoryImage(undefined); // Clear previous image
    try {
      const { story: generatedStory, imageUrl } = await generateHistoryStory(prompt, style, length, language);
      setStory(generatedStory);
      setStoryImage(imageUrl);
    } catch (error: any) {
      console.error(error);
      if (error.message.includes("Requested entity was not found.")) {
        alert("API key error: Please ensure you have selected a valid paid API key for image generation. Opening key selection dialog.");
        setHasApiKey(false);
        await handleApiKeySelection();
      }
      setStory("Kshama karein, kahani sunane mein kuch takleef ho rahi hai.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    checkApiKey();
  }, []);

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Itihas ki Kahani',
          text: 'Check out this historical story generated by AI!',
          url: window.location.href,
        });
        setShareMessage('Kahani share ho gayi!');
        setTimeout(() => setShareMessage(null), 3000);
      } catch (error) {
        console.error('Error sharing:', error);
        setShareMessage('Share karne mein takleef hui.');
        setTimeout(() => setShareMessage(null), 3000);
      }
    } else {
      alert('Aapka browser sharing support nahi karta hai.');
    }
  };

  const refreshStory = async () => {
    if (!hasApiKey) {
      alert('Please select an API key to generate stories with images.');
      await handleApiKeySelection();
      return;
    }

    setLoading(true);
    setStoryImage(undefined); // Clear previous image
    try {
      const { story: generatedStory, imageUrl } = await generateHistoryStory(userPrompt, narrativeStyle, storyLength, selectedLanguage);
      setStory(generatedStory);
      setStoryImage(imageUrl);
    } catch (error: any) {
      console.error(error);
      if (error.message.includes("Requested entity was not found.")) {
        alert("API key error: Please ensure you have selected a valid paid API key for image generation. Opening key selection dialog.");
        setHasApiKey(false);
        await handleApiKeySelection();
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#f5f2ed] text-[#1a1a1a] font-serif selection:bg-[#5A5A40] selection:text-white">
      <AnimatePresence mode="wait">
        {step === 'entry' ? (
          <motion.div
            key="entry"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0, y: -20 }}
            className="fixed inset-0 flex flex-col items-center justify-center p-6 text-center"
          >
            <motion.div
              initial={{ scale: 0.8, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              transition={{ delay: 0.2 }}
              className="mb-8"
            >
              <div className="w-24 h-24 bg-[#5A5A40] rounded-full flex items-center justify-center mx-auto mb-6 shadow-xl">
                <User size={48} className="text-white" />
              </div>
              <h1 className="text-5xl md:text-7xl font-light tracking-tight mb-2">
                Swagat hai, <span className="italic font-normal">Sunny Vaishnav</span>
              </h1>
              <p className="text-xl opacity-60 max-w-md mx-auto">
                Itihas ke panno ko palatne ka samay aa gaya hai.
              </p>
              <textarea
                className="w-full max-w-md p-4 mt-6 rounded-lg border border-[#1a1a1a]/20 bg-white/50 backdrop-blur-sm focus:outline-none focus:border-[#5A5A40] transition-colors text-lg"
                placeholder="Apni kahani ke liye ek prompt likhein... (Jaise: Prachin Bharat ke raja, ya Duniya ki sabse purani sabhyata)"
                value={userPrompt}
                onChange={(e) => setUserPrompt(e.target.value)}
                rows={4}
              ></textarea>

              <div className="w-full max-w-md mt-4 text-left">
                <label htmlFor="narrative-style" className="block text-sm font-sans font-medium text-[#1a1a1a]/70 mb-2">
                  Kahani ki Shaili:
                </label>
                <select
                  id="narrative-style"
                  className="w-full p-3 rounded-lg border border-[#1a1a1a]/20 bg-white/50 backdrop-blur-sm focus:outline-none focus:border-[#5A5A40] transition-colors text-lg"
                  value={narrativeStyle}
                  onChange={(e) => setNarrativeStyle(e.target.value)}
                >
                  {narrativeStyles.map((style) => (
                    <option key={style.value} value={style.value}>
                      {style.label}
                    </option>
                  ))}
                </select>
              </div>

              <div className="w-full max-w-md mt-4 text-left">
                <label htmlFor="story-length" className="block text-sm font-sans font-medium text-[#1a1a1a]/70 mb-2">
                  Kahani ki Lambai:
                </label>
                <select
                  id="story-length"
                  className="w-full p-3 rounded-lg border border-[#1a1a1a]/20 bg-white/50 backdrop-blur-sm focus:outline-none focus:border-[#5A5A40] transition-colors text-lg"
                  value={storyLength}
                  onChange={(e) => setStoryLength(e.target.value)}
                >
                  {storyLengths.map((length) => (
                    <option key={length.value} value={length.value}>
                      {length.label}
                    </option>
                  ))}
                </select>
              </div>
            </motion.div>

            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={() => startStory(userPrompt, narrativeStyle, 'long', selectedLanguage)}
              className={cn(
                "bg-[#5A5A40] text-white px-10 py-4 rounded-full text-lg font-medium shadow-lg hover:bg-[#4a4a35] transition-colors flex items-center gap-3",
                !hasApiKey && "opacity-50 cursor-not-allowed"
              )}
              disabled={!hasApiKey}
            >
              <BookOpen size={20} />
              Kahani Shuru Karein
            </motion.button>

            {!hasApiKey && (
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                onClick={handleApiKeySelection}
                className="mt-4 bg-blue-600 text-white px-8 py-3 rounded-full text-base font-medium shadow-lg hover:bg-blue-700 transition-colors flex items-center gap-2"
              >
                <User size={18} />
                API Key Select Karein
              </motion.button>
            )}
          </motion.div>
        ) : (
          <motion.main
            key="story"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-4xl mx-auto px-6 py-12 md:py-24"
          >
            <header className="mb-16 border-b border-[#1a1a1a]/10 pb-8 flex justify-between items-end">
              <div>
                <div className="flex items-center gap-2 text-[#5A5A40] mb-4">
                  <History size={20} />
                  <span className="uppercase tracking-[0.2em] text-xs font-sans font-bold">Prachin Itihas</span>
                </div>
                <h2 className="text-4xl md:text-6xl font-light">Itihas ki Kahani</h2>
              </div>
              <div className="flex items-center gap-2">
                {shareMessage && (
                  <motion.div
                    initial={{ opacity: 0, y: -10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -10 }}
                    className="absolute top-full right-0 mt-2 p-2 bg-green-500 text-white text-sm rounded-md shadow-lg"
                  >
                    {shareMessage}
                  </motion.div>
                )}
                <button 
                  onClick={handleShare}
                  className="p-3 rounded-full border border-[#1a1a1a]/10 hover:bg-[#1a1a1a]/5 transition-colors"
                  title="Kahani Share Karein"
                >
                  <Share2 size={20} />
                </button>
                <button 
                  onClick={refreshStory}
                  disabled={loading}
                  className="p-3 rounded-full border border-[#1a1a1a]/10 hover:bg-[#1a1a1a]/5 transition-colors disabled:opacity-50"
                  title="Nayi Kahani"
                >
                  <RefreshCw size={20} className={cn(loading && "animate-spin")} />
                </button>
                <DropdownMenu>
                  <DropdownMenuItem onClick={() => console.log('Search clicked')}>
                    <div className="flex items-center gap-2">
                      <Search size={16} />
                      <span>Search (Coming Soon)</span>
                    </div>
                  </DropdownMenuItem>
                  <div className="border-t border-[#1a1a1a]/10 my-1" />
                  <div className="px-4 py-2 text-sm text-[#1a1a1a]/70">Bhasha</div>
                  {languages.map((lang) => (
                    <DropdownMenuItem 
                      key={lang.value}
                      onClick={() => {
                        setSelectedLanguage(lang.value);
                        // Optionally refresh story with new language
                        refreshStory();
                      }}
                      className={cn(selectedLanguage === lang.value && 'bg-[#f5f2ed] font-medium')}
                    >
                      {lang.label}
                    </DropdownMenuItem>
                  ))}
                </DropdownMenu>
              </div>
            </header>

            <div className="relative">
              {loading ? (
                <div className="flex flex-col items-center justify-center py-20 gap-4 opacity-40">
                  <Loader2 size={48} className="animate-spin" />
                  <p className="italic">Puraane panno ko dhundha ja raha hai...</p>
                </div>
              ) : (
                <motion.article
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="prose prose-stone prose-lg max-w-none"
                >
                  <div className="bg-white/50 backdrop-blur-sm p-8 md:p-12 rounded-[32px] shadow-sm border border-white/20 leading-relaxed text-xl">
                    {storyImage && (
                      <motion.img
                        key={storyImage}
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        src={storyImage}
                        alt="Generated historical image"
                        className="w-full h-auto rounded-xl mb-8 shadow-md object-cover"
                        referrerPolicy="no-referrer"
                      />
                    )}
                    <ReactMarkdown>{story}</ReactMarkdown>
                  </div>
                  
                  <div className="mt-12 flex items-center justify-center gap-4 opacity-30">
                    <div className="h-px w-12 bg-[#1a1a1a]" />
                    <Scroll size={24} />
                    <div className="h-px w-12 bg-[#1a1a1a]" />
                  </div>
                </motion.article>
              )}
            </div>

            <footer className="mt-24 text-center opacity-40 text-sm font-sans uppercase tracking-widest">
              Sunny Vaishnav &bull; Itihas ki Kahaniyan
            </footer>
          </motion.main>
        )}
      </AnimatePresence>
    </div>
  );
}
